### ISSUE TITLE
Add same point twice, not on curve

### ISSUE THREAD

**Issue by jeffallen** [cloudflare/bn256#11]
While investigating dedis/kyber#400, I found that this package (which kyber is derived from) has a behaviour that seems surprising. After adding a point to itself, it is no longer on the curve. If you add two unrelated points, the point stays on the curve:

```
func TestG2_2add(t *testing.T) {
	_, Ga, err := RandomG2(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	_, Gb, err := RandomG2(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	Ga.Add(Ga, Gb)
	require.True(t, Ga.p.IsOnCurve())
	Ga.Add(Ga, Ga)
	require.True(t, Ga.p.IsOnCurve())
}

func TestG2_2mul(t *testing.T) {
	_, Ga, err := RandomG2(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	two := bigFromBase10("2")
	Ga.ScalarMult(Ga, two)
	ma := Ga.Marshal()

	_, err = Ga.Unmarshal(ma)
	// fails due to "bn256: malformed point"
	require.NoError(t, err)
}
```

As the second test shows, multiply by 2 also creates this situation where the twistPoint is no longer on the curve (detected by the IsOnCurve inside of Unmarshal).

Thanks to @tobowers and @daeinar for help finding this.

**Comment by Bren2010** [comment]
Great, thanks
