### ISSUE TITLE
Cannot unmarshal a G2 point when loaded as part of a plugin

### ISSUE THREAD

**Issue by timorl** [cloudflare/bn256#16]
I tried using this package inside a go `plugin` and it doesn't work as expected. When attempting to `Unmarshal()` a `G2`, a "bn256: malformed point" error is returned.

I made a minimal example [here](https://gitlab.com/tymorl/xenophobia). I checked the bug with versions 1.12.13 and 1.13.5 of go.

I suspect this might be the result of using assembly, but I never used assembly in go, so I don't have the expertise to properly check this hypothesis. If this is the case it's probably more of a go issue, but I wanted to ask here first, maybe you can help me somehow.

Sorry for not using the template the contributing guidelines mention, but I couldn't find it.

**Comment by timorl** [comment]
I stole a minimal assembly example and added it to my repo. Unfortunately this does not explain the problem, because that example works. Now I am out of ideas. :/

**Comment by timorl** [comment]
Made the example more deterministic and now I am sure the problem is somewhere in the asm usage -- deleting the `*_amd64.s` file and modifying the respective generic file to compile on amd64 makes plugins work. Thanks for help @robryk.

**Comment by Bren2010** [comment]
I further simplified your code: https://github.com/Bren2010/xenophobia/. The issue is that R15 is being stomped when outside variables are loaded (see line 3 in `pkg/demo/demo_amd64.s`). Let me know if you want to open a ticket with Golang or if I should.

Current recommendation is to build the plugin with `-tags=generic`.

**Comment by timorl** [comment]
I reported the issue, but it seems they are aware and probably unwilling to change this behaviour, see [here](https://github.com/golang/go/issues/18820). The solutions in that bug replaced outside variables with `define`s, but I don't know how feasible this approach would be in this repo.

Thank you very much for your help! Especially for the `tags=generic` thing, now at least I can keep developing before this is resolved.
