### ISSUE TITLE
adapt to go 1.17

### ISSUE THREAD

**Issue by shinyxhh** [cloudflare/bn256#26]
![image](https://user-images.githubusercontent.com/78244264/173060291-c7063614-0a10-4fce-ba80-6b1447d4cd72.png)

**Comment by shinyxhh** [comment]
errors building in go 1.17

**Comment by armfazh** [comment]
the error shown in the image corresponds to the [gurvy](https://github.com/ConsenSys/gnark-crypto/tree/v0.3.8) package.

For bn256, the issue was already solved in https://github.com/cloudflare/bn256/commit/9bd9f73a0273ed2f42707ed13b3e36d38baa2a49

**Comment by shinyxhh** [comment]
yes, i have replaced version of bn256, and i thought it didn't work. sorry for my mistake, and thank you for your reply. i am going to put up an issue for gurvy.
