### ISSUE TITLE
Which algorithm does mulLine() use?

### ISSUE THREAD

**Issue by xhliu** [cloudflare/bn256#29]
I have not found it in [Faster Computation of the Tate Pairing](http://arxiv.org/pdf/0904.0854v3.pdf) or http://cryptojedi.org/papers/dclxvi-20100714.pdf.
https://github.com/cloudflare/bn256/blob/9bd9f73a0273ed2f42707ed13b3e36d38baa2a49/optate.go#L94

**Comment by armfazh** [comment]
The mulLine function is performing the product between the accumulator element in Fp12 and the line represented in a compact form by 3 Fp2 elements.
So mulLine is not computing any line function, only the multiplication.

![image](https://user-images.githubusercontent.com/10335519/176543635-18b7c179-ad1d-4766-a8c0-c20e271993bc.png)


A similar pairing was implemented in https://eprint.iacr.org/2010/354.pdf
and in Algorithm 21 expresses what mulLine is computing.

**Comment by xhliu** [comment]
Could you elaborate on how the notations in the [paper](https://eprint.iacr.org/2010/354.pdf) map to the variables in [code](https://github.com/cloudflare/bn256/blob/9bd9f73a0273ed2f42707ed13b3e36d38baa2a49/optate.go#L94)? Is it as follows?

```
ret -> A
ret.x -> a0
ret.y -> a1
 
a -> b00
b -> b10
c -> b11
```

Also, where can I why **a**, **b**, and **c** are defined the way they are in [lineFunctionAdd](https://github.com/cloudflare/bn256/blob/9bd9f73a0273ed2f42707ed13b3e36d38baa2a49/optate.go#L3) and [lineFunctionDouble](https://github.com/cloudflare/bn256/blob/9bd9f73a0273ed2f42707ed13b3e36d38baa2a49/optate.go#L52)? E.g., **a**

https://github.com/cloudflare/bn256/blob/9bd9f73a0273ed2f42707ed13b3e36d38baa2a49/optate.go#L41

https://github.com/cloudflare/bn256/blob/9bd9f73a0273ed2f42707ed13b3e36d38baa2a49/optate.go#L83-L86

Thanks in advance.

**Comment by armfazh** [comment]
Check Algorithms 26 and 27 of ia.cr/2010/354
As you may notice, the line evaluations returns an element of Fp12, which is represented as two elements in Fp6. However, each of these elements have some components zeroed. 

I haven't check whether this is the exact mapping, but it's not difficult to figure out. Just note how the field tower is constructed. 
Check Section 4.1 of ia.cr/2010/354, and note that there are two possible representations of Fp12, one that uses Fp2, and one that uses Fp6 as subfields.

In the code, they switch between these representations. Also take a look of cryptojedi's [code](https://www.cryptojedi.org/crypto/#dclxvi)
