### ISSUE TITLE
[lattices] Leaking bit sizes during scalar recoding

### ISSUE THREAD

**Issue by mratsim** [cloudflare/bn256#42]
This is not in the master branch but on the lattices branch.

After the (potentially secret) scalar decomposition, the following code uses a branch `if x.BitLen() > maxLen` that depends on the scalar hence on potentially secret data:

https://github.com/cloudflare/bn256/blob/be78db46651cd48a5adfcfaf61384112e3562613/lattice.go#L87-L95

_edit: Reading the scalar mul and addition, seems like in general the code isn't constant-time. Feel free to close in that case._

**Comment by armfazh** [comment]
Correct, the implementation does not assume constant-time operations, indeed relying on `big.Int` operations is assumed to be non-constant-time.
As well as operations using pre-computed tables also require protection.
