### ISSUE TITLE
Security level clarification

### ISSUE THREAD

**Issue by mdempsky** [cloudflare/bn256#7]
https://godoc.org/golang.org/x/crypto/bn256 refers to this package as a faster implementation, but also warns that neither version provides 128-bit security.

However, https://godoc.org/github.com/cloudflare/bn256 still says it offers 128-bit security.

Presumably the cloudflare/bn256 documentation should be updated similarly to the x/crypto/bn256 documentation?

(Disclaimer: I don't know anything about bn256, the linked moderncrypto post is jibberish to me.)

**Comment by armfazh** [comment]
According to recent improvements made in [1], the BN256 does not offer 128-bit security.
Documentation must be updated. 
A shift to stronger curves is recommended, for example those reported in [2].

[1] https://eprint.iacr.org/2015/1027.pdf
[2] https://eprint.iacr.org/2017/334.pdf

**Comment by Bren2010** [comment]
@mdempsky Thanks for the heads-up, the documentation has been updated.
